### ISSUE TITLE
Package not found exception on executing "installed" version

### ISSUE THREAD

**Issue by luksus42** [pobrn/ite8291r3-ctl#1]
Hi,
if I execute the version, which I installed by pip get this error:
```bash
sudo ite8291r3-ctl -h                         
Traceback (most recent call last):
  File "/home/luke/.local/bin/ite8291r3-ctl", line 33, in <module>
    sys.exit(load_entry_point('ite8291r3-ctl==0.2', 'console_scripts', 'ite8291r3-ctl')())
  File "/home/luke/.local/bin/ite8291r3-ctl", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ite8291r3-ctl

```
when executing it manually from the source with `sudo python -m ite8291r3_ctl -h` everything works as expected.

Maybe it is an issue with my python config, but perhaps you have a helpful advice anyway.
Thanks,
Lukas

**Comment by luksus42** [comment]
after adding a udev rule, it works...

**Comment by pobrn** [comment]
Sorry, I haven't received notifications for this repository, and I've just seen this issue. Glad it worked in the end.
